#pragma once

#define SEAD_VERSION_NONE      0
#define SEAD_VERSION_REDPEPPER 1
#define SEAD_VERSION_CTRDASH   2
#define SEAD_VERSION_GARDEN    3
#define SEAD_VERSION_BIGRED    4

#ifndef SEAD_VERSION
#define SEAD_VERSION SEAD_VERSION_REDPEPPER /* Default */
#endif

/* TODO RESEARCH ON */

#if SEAD_VERSION == SEAD_VERSION_REDPEPPER

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#elif SEAD_VERSION == SEAD_VERSION_CTRDASH

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#elif SEAD_VERSION == SEAD_VERSION_GARDEN

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#elif SEAD_VERSION == SEAD_VERSION_BIGRED

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#endif