#pragma once

#define SEAD_VERSION_NONE      0
#define SEAD_VERSION_REDPEPPER 1
#define SEAD_VERSION_CTRDASH   2
#define SEAD_VERSION_GARDEN    3
#define SEAD_VERSION_BIGRED    4

#ifndef SEAD_VERSION
#define SEAD_VERSION SEAD_VERSION_REDPEPPER /* Default */
#endif

/// sead version features:
///
/// SEAD_CTRCONTROLLER_STATIC:
///     Makes getControlDevice() CtrController / CtrDebugController static/
/// SEAD_CTRFILESTREAM_DOCLOSE_FLUSH:
///     Makes doClose_() in call nn::fs::Directory::TryFlush()


#if SEAD_VERSION == SEAD_VERSION_REDPEPPER

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#define SEAD_CTRCONTROLLER_STATIC 0
#define SEAD_CTRFILESTREAM_DOCLOSE_FLUSH  0
#define SEAD_CTRFILESTREAM_

#elif SEAD_VERSION == SEAD_VERSION_CTRDASH

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#define SEAD_CTRCONTROLLER_STATIC 0
#define SEAD_CTRFILESTREAM_DOCLOSE_FLUSH 1

#elif SEAD_VERSION == SEAD_VERSION_GARDEN

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR 9
#define SEAD_VERSION_MICRO 0
#define SEAD_VERSION_PATCH 3 // maybe

#define SEAD_CTRCONTROLLER_STATIC 1
#define SEAD_CTRFILESTREAM_DOCLOSE_FLUSH 1

#elif SEAD_VERSION == SEAD_VERSION_BIGRED

#define SEAD_VERSION_MAJOR 0
#define SEAD_VERSION_MINOR
#define SEAD_VERSION_MICRO
#define SEAD_VERSION_PATCH

#define SEAD_CTRCONTROLLER_STATIC 0 /* research */
#define SEAD_CTRFILESTREAM_DOCLOSE_FLUSH 1

#endif